name: responsive
description: A new Flutter project.
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: '>=2.19.1 <3.0.0'
dependencies:
  flutter:
    sdk: flutter

  # NETWORK CALLS
  url_launcher: ^6.1.10
  image_picker: ^0.8.7
  dio: ^5.0.2

  # STATE MANAGEMENT
  provider: ^6.0.5

  # IMAGES
  cupertino_icons: ^1.0.2
  cached_network_image: ^3.2.3
  bot_toast: ^4.0.3
  

  # OTHERS
  



dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  
flutter:

  uses-material-design: true

  
  # assets:
  #   - images/a_dot_burr.jpeg

 
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
 
